name: flutter_todo # Название проекта
description: A new Flutter project. # Описание проекта
publish_to: 'none' # Настройка публикации проекта
version: 0.1.0 # Версия проекта

environment: # Настройка окружения проекта
 sdk: '>=3.0.5 <4.0.0' # Версия SDK для проекта

dependencies: # Зависимости проекта
 flutter: # Зависимость Flutter SDK
  sdk: flutter
 
 cupertino_icons: ^1.0.5 # Зависимость для иконок iOS в стиле Cupertino
 
 uuid: ^3.0.7 # Зависимость для генерации уникальных идентификаторов
 flutter_slidable: ^3.0.0 # Зависимость для создания скользящих элементов в интерфейсе

 hydrated_bloc: ^9.1.2 # Зависимость для установки прослойки между блоками состояний и хранилищем
 path_provider: ^2.0.15 # Зависимость для получения информации о файловой системе устройства
 flutter_bloc: ^8.1.3 # Зависимость для работы с блоками состояний
 equatable: ^2.0.5 # Зависимость для упрощения сравнения объектов
 meta: ^1.9.1 # Зависимость для применения метаданных к классам и методам
 bloc: ^8.1.2 # Зависимость для реализации паттерна блоков состояний

dev_dependencies: # Зависимости для разработки проекта
 flutter_test: # Зависимость для тестирования Flutter приложений
  sdk: flutter
 flutter_lints: ^2.0.0 # Зависимость для проверки соответствия кода рекомендациям по стилю

flutter: # Настройки Flutter
 uses-material-design: true # Использование дизайна в стиле Material Design